-- drop table if EXISTS items_requests cascade;
-- drop table if EXISTS bookings cascade;
-- drop table if EXISTS comments cascade;
-- drop table if EXISTS items cascade;
-- drop table if EXISTS users cascade;

CREATE TABLE IF NOT EXISTS users (
     user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
     name VARCHAR(255) NOT NULL,
     email VARCHAR(512) NOT NULL,

     CONSTRAINT pk_user PRIMARY KEY (user_id),
     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);