-- drop table if EXISTS items_requests cascade;
-- drop table if EXISTS bookings cascade;
-- drop table if EXISTS comments cascade;
-- drop table if EXISTS items cascade;
-- drop table if EXISTS users cascade;

CREATE TABLE IF NOT EXISTS hits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(512) NOT NULL,
    ip VARCHAR(255) NOT NULL,
    timestamp VARCHAR(512) NOT NULL,

    CONSTRAINT pk_user PRIMARY KEY (id)
);